import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

export default new Vuex.Store({
    state: {
        messageData: [
            {
                id: 1,
                firstName: 'Tamara',
                lastName: 'Einstein',
                email: 'tamara@mstamara.io',
                image: 'image10.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '09:03 AM',
                is_active: true,
            },
            {
                id: 2,
                firstName: 'Candy',
                lastName: 'Austen',
                email: 'candy.austen@mail.com',
                image: 'image2.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '10:05 AM',
                is_active: false,
            },
            {
                id: 3,
                firstName: 'Crystal',
                lastName: 'Machine',
                email: 'crystal.austen@mail.com',
                image: 'image3.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '10:30 AM',
                is_active: false,
            },
            {
                id: 4,
                firstName: 'Delli',
                lastName: 'Frasberg',
                email: 'h1@delli.au',
                image: 'image4.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '10:45 AM',
                is_active: true,
            },
            {
                id: 5,
                firstName: 'Sheila',
                lastName: 'Bushido',
                email: 'sheila.japan@gmail.com',
                image: 'image5.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '10:45 AM',
                is_active: false,
            },
            {
                id: 6,
                firstName: 'Natasha',
                lastName: 'Whitman',
                email: 'natasha.dev@msfconsole.com',
                image: 'image6.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '11:23 AM',
                is_active: true,
            },
            {
                id: 7,
                firstName: 'Sarah',
                lastName: 'Webber',
                email: 'webber@mail.ru',
                image: 'image7.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '11:45 AM',
                is_active: true,
            },
            {
                id: 8,
                firstName: 'Monica',
                lastName: 'Monaco',
                email: 'moana@monaco.mu',
                image: 'image9.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '12:23 PM',
                is_active: false,
            },
            {
                id: 9,
                firstName: 'Jaykob',
                lastName: 'Wiseman',
                email: 'hello@jaykobpc.dev',
                image: 'image8.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '12:30 PM',
                is_active: true,
            },
        ],
        contactData: [
            {
                id: 1,
                firstName: 'Andrew',
                lastName: 'Austen',
                email: 'andrew.austen@mail.com',
                image: 'image1.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi!',
                time: '09:54 AM',
                is_active: true,
            },
            {
                id: 2,
                firstName: 'Candy',
                lastName: 'Austen',
                email: 'candy.austen@mail.com',
                image: 'image2.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '10:05 AM',
                is_active: false,
            },
            {
                id: 3,
                firstName: 'Crystal',
                lastName: 'Machine',
                email: 'crystal.austen@mail.com',
                image: 'image3.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '10:30 AM',
                is_active: false,
            },
            {
                id: 4,
                firstName: 'Delli',
                lastName: 'Frasberg',
                email: 'wassup@delli.au',
                image: 'image4.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '10:45 AM',
                is_active: true,
            },
            {
                id: 5,
                firstName: 'Sheila',
                lastName: 'Bushido',
                email: 'sheila.japan@gmail.com',
                image: 'image5.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '10:45 AM',
                is_active: false,
            },
            {
                id: 6,
                firstName: 'Natasha',
                lastName: 'Whitman',
                email: 'natasha.dev@msfconsole.com',
                image: 'image9.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '11:23 AM',
                is_active: true,
            },
            {
                id: 7,
                firstName: 'Sarah',
                lastName: 'Webber',
                email: 'webber@mail.ru',
                image: 'image7.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '11:45 AM',
                is_active: true,
            },
            {
                id: 8,
                firstName: 'Monica',
                lastName: 'Monaco',
                email: 'moana@monaco.mu',
                image: 'image8.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '12:23 PM',
                is_active: false,
            },
            {
                id: 9,
                firstName: 'Jaykob',
                lastName: 'Wiseman',
                email: 'hello@jaykobpc.dev',
                image: 'image6.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '12:30 PM',
                is_active: true,
            },
            {
                id: 10,
                firstName: 'Tamara',
                lastName: 'Einstein',
                email: 'tamara@mstamara.io',
                image: 'image10.jpeg',
                text: 'Lorem ipsum dolor sit amet consectetur et facere animi dolore!',
                time: '13:03 PM',
                is_active: true,
            },
        ]
    }
});